### ISSUE TITLE
schedule:render with schedule ID and name

### ISSUE THREAD

**Issue by sdenef-adeo** [martindstone/pagerduty-cli#28]
Hello,

I need to use `schedule:render` then use the result to join escalation policies, teams, or whatever.
I faced an issue because I'm not able to have the schedule ID and/or name. As far as I understand, the schedule:render command restrict data to the `schedule.final_schedule.rendered_schedule_entries` part.
I didn't find any way to add schedule ID and name to the ouput.

Any idea? Or is it a feature request to implement?

Example:
`pd schedule render -i P999999 --since=$PD_SINCE --until=$PD_UNTIL --sort=start --output=csv --delimiter=,`
Output:
```
Start,End,Duration,User id,User name
"27/05/2022, 00:00:00","27/05/2022, 23:59:59","23 hours","PU00000","John Doe"
```
Expected:
```
Schedule id,Schedule name,Start,End,Duration,User id,User name
"PSSSSSS",""my schedule","27/05/2022, 00:00:00","27/05/2022, 23:59:59","23 hours","PU00000","John Doe"
```

Regards,
Sébastien

**Comment by martindstone** [comment]
Hi @sdenef-adeo , I guess I thought that since this command can only render one schedule at a time, nobody would need the id and the name because they would already have known it. But I sort of get what you are trying to do. How about if i add those values as extended columns that will be shown if you give the `-x` flag?

**Comment by sdenef-adeo** [comment]
Hi Martin,
I tested and it works well. Thank you.

**Comment by martindstone** [comment]
Awesome. I will close this issue now. Thanks for reporting it!
