### ISSUE TITLE
pd team:user:list only shows the first 25 users of the team instead of all

### ISSUE THREAD

**Issue by maxchen-000** [martindstone/pagerduty-cli#8]
for some reason "pd team:user:list: command only shows the first 25 users of the team instead of all users of that team

**Comment by martindstone** [comment]
Hi, thanks for reporting this! It looks like this is a bug with the endpoint, it is not filling in the total element for proper pagination. I've raised this with our product team and hope to have a resolution or a workaround soon. Thanks...

**Comment by martindstone** [comment]
Hi again, I have just pushed a version that has a workaround for this problem. It will just send requests in series rather than in parallel if the `total` element is missing. When the endpoint gets fixed, the command will just get slightly faster :)

Please update to version 0.0.69 and let me know if this is resolved for you. Thanks!

**Comment by maxchen-000** [comment]
Yes, it's working now with version 0.0.69. Thanks

**Comment by martindstone** [comment]
Great! I will close this issue now. Thanks again for reporting it.
